Content:
    - ${ROOT_DIR}/doc/content
    - ${MOOSE_DIR}/framework/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: Magpie
    repo: https://github.com/idaholab/magpie
    home: http://mooseframework.org/magpie

Extensions:
    MooseDocs.extensions.navigation:
        name: 'Magpie'
        repo: https://github.com/idaholab/magpie
        home: https://www.mooseframework.org/magpie
        menu:
            Getting Started:
                Installation: 'getting_started/Installation.md'
                Marmot coupling: 'getting_started/Marmot.md'
            # Development:
                #     Capabilities: 'models_capabilities/Capabilities.md'
                #     Requirements: 'software_quality/Requirements.md'
            Documentation:
                Reference Manual: syntax/index.md

    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        hide:
            magpie: !include ${ROOT_DIR}/doc/hidden.yml
            framework: !include ${MOOSE_DIR}/framework/doc/hidden.yml
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml

    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml

    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
